# Generated by Django 3.1.1 on 2020-09-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
    ]
